create table tbl_job_categoryC(
    id bigint unsigned auto_increment primary key,
    job_categoryC_name varchar(255),
    job_categoryB_id bigint unsigned not null,
    constraint fk_job_categoryC_job_categoryB foreign key (job_categoryB_id)
        references tbl_job_categoryB(id)
);

select * from tbl_job_categoryC;

-- 직무·직업 (ID = 3)
INSERT INTO tbl_job_categoryC (job_categoryC_name, job_categoryB_id)
VALUES
    ('광고PD', 3),
    ('광고마케팅', 3),
    ('글로벌마케팅', 3),
    ('기업홍보', 3),
    ('디지털마케팅', 3),
    ('마케팅', 3),
    ('마케팅기획', 3),
    ('마케팅전략', 3),
    ('모바일마케팅', 3),
    ('미디어플래너', 3),
    ('바이럴마케팅', 3),
    ('병원마케팅', 3),
    ('브랜드마케팅', 3),
    ('블로그마케팅', 3),
    ('비즈니스마케팅', 3),
    ('스포츠마케팅', 3),
    ('오프라인마케팅', 3),
    ('온라인마케팅', 3),
    ('인플루언서마케팅', 3),
    ('제휴마케팅', 3),
    ('조사원', 3),
    ('체험마케팅', 3),
    ('콘텐츠기획', 3),
    ('콘텐츠마케팅', 3),
    ('콘텐츠에디터', 3),
    ('퍼포먼스마케팅', 3),
    ('프로덕트마케팅', 3),
    ('행사기획', 3),
    ('홍보', 3),
    ('AD(아트디렉터)', 3),
    ('AE(광고기획자)', 3),
    ('AM(어카운트매니저)', 3),
    ('B2B마케팅', 3),
    ('BM(브랜드매니저)', 3),
    ('CBO', 3),
    ('CD(크리에이티브디렉터)', 3),
    ('CMO', 3),
    ('CRM마케팅', 3),
    ('CW(카피라이터)', 3),
    ('MW(메디컬라이터)', 3),
    ('SNS마케팅', 3);

-- 전문 분야 (ID = 4)
INSERT INTO tbl_job_categoryC (job_categoryC_name, job_categoryB_id)
VALUES
    ('검색광고', 4),
    ('광고주관리', 4),
    ('광고캠페인', 4),
    ('그로스해킹', 4),
    ('라이센싱', 4),
    ('매체관리', 4),
    ('배너광고', 4),
    ('비딩', 4),
    ('사보/뉴스레터', 4),
    ('사회조사', 4),
    ('설문조사', 4),
    ('세일즈프로모션', 4),
    ('시장조사', 4),
    ('언론홍보', 4),
    ('옥외광고', 4),
    ('이벤트프로모션', 4),
    ('채널관리', 4),
    ('키워드광고', 4),
    ('통계/분석', 4),
    ('퍼블리시티', 4),
    ('ATL', 4),
    ('BTL', 4),
    ('IMC', 4),
    ('MCN', 4),
    ('MICE', 4),
    ('PPL', 4),
    ('RFP(제안요청서)', 4),
    ('SEO', 4);
